services:
  api:
    build: .
    image: os-tuto-idempotent-api:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Data Source=/data/idempotent.db
    volumes:
      - dbdata:/data

volumes:
  dbdata:
